name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - uses: actions/checkout@v2

      # Set up Python (specify the version you need)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies from requirements.txt (if it exists)
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      # Install pytest if not in requirements.txt
      - name: Install pytest
        run: pip install pytest

      # Run tests (adjust file path if necessary)
      - name: Run tests
        run: pytest UnitTest.py
